### ISSUE TITLE
MIT in pyproject.toml

### ISSUE THREAD

**Issue by hyandell** [rocioar/flake8-django#101]
Just noting that you have MIT set as the licensing classifier in the pyproject.toml. Presumably not the intent with the license metadata saying GPL-3.0 and README saying GPL.

**Comment by adamchainz** [comment]
I'd prefer, if possible, that the maintainers re-license as MIT. Yes, technically linter plugins can be GPL without affecting your code's licensing, since you don't import them. But any GPL package will be flagged in an audit, and some orgs won't even allow adopting GPL packages in the first place.
