### ISSUE TITLE
Add check for __str__ method defined in models

### ISSUE THREAD

**Issue by rocioar** [rocioar/flake8-django#14]
__str__ method should be present in all models defined in the project.

__str__ method will define how the data will be represented in the Django admin.

**Comment by rocioar** [comment]
@rodolfolottin sure! go ahead.

**Comment by rodolfolottin** [comment]
How are u doing to manually test the new checkers that you are creating? I mean, do you create a django app and define a Model?

I checked your checkers and you are providing a string with the code that you want to be checked, but in this case (checking for the `__str__` method), following your approach, I would have to give a multi line string to the checker representing the model that I want?

**Comment by rocioar** [comment]
@rodolfolottin in this case is probably better to write some code on a file and then use an utility function, that you can put it inside tests/utils.py to read the file and run the checks against it.

**Comment by rocioar** [comment]
Also a good source for learning mode about the nodes: https://greentreesnakes.readthedocs.io/en/latest/nodes.html

They also have prettyprinter that's really nice: https://bitbucket.org/takluyver/greentreesnakes/src/default/astpp.py

**Comment by rodolfolottin** [comment]
Thank you! This weekend I'll have some time to work on it.
