### ISSUE TITLE
Add check for order of Model inner classes and methods

### ISSUE THREAD

**Issue by rocioar** [rocioar/flake8-django#18]
Order should be as follows:

- All database fields
- Custom manager attributes
- class Meta
- def __str__()
- def save()
- def get_absolute_url()
- Any custom methods

Taken from: [Django Coding Style](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#model-style)

**Comment by rodolfolottin** [comment]
Is anyone working on it? I could help with that.

**Comment by rocioar** [comment]
@rodolfolottin go ahead if you wish 👍

**Comment by denizdogan** [comment]
Unless someone else has picked this up, I will give this a go over the weekend.

**Comment by rocioar** [comment]
@denizdogan no one else has picked it, that would be great. Thanks!
