### ISSUE TITLE
BooleanField with null=True in Django 2.1 with DJ02

### ISSUE THREAD

**Issue by browniebroke** [rocioar/flake8-django#22]
First of all, thanks for starting this, it's a super cool idea and has already many interesting checks.

I recently came across a change in [2.1 regarding BooleanField](https://docs.djangoproject.com/en/2.1/ref/models/fields/#django.db.models.BooleanField), which seems to contradict one of the checks (DJ02):

>  Changed in Django 2.1:
> 
> In older versions, this field doesn’t permit null=True, so you have to use NullBooleanField instead. Using the latter is now discouraged as it’s likely to be deprecated in a future version of Django.

Is the DJ02 check incompatible with Django 2.1+ or do I misunderstand it? I know that `null` and `blank` have slightly different meaning usually, but feels like a special case `BooleanField`, no?

**Comment by rocioar** [comment]
Thanks for bringing this up, I didn't know about it, and I agree with you that it makes DJ02 obsolete.

We should remove it.

**Comment by rocioar** [comment]
Actually now that I've digged a bit deeper into code and the DJ02 check itself, I realised that the message is wrong, the check is correct, DJ02 is checking [not blank=True](https://github.com/rocioar/flake8-django/blob/master/checkers/model_fields.py#L41) fields.

Instead what I should do is remove BooleanField from the list of [NOT_NULL_TRUE_FIELDS](https://github.com/rocioar/flake8-django/blob/master/checkers/model_fields.py#L5). And fix the message on DJ02.

Thanks!
