### ISSUE TITLE
Add a linter - Proposal

### ISSUE THREAD

**Issue by rodolfolottin** [rocioar/flake8-django#24]
What do you think about using a linter? We have a few options, like: [black](https://github.com/ambv/black), [yapf](https://github.com/google/yapf) and the own [flake8](https://github.com/PyCQA/flake8).

Black is getting quite of famous these days.

**Comment by rocioar** [comment]
We are currently using CircleCI to run the tests, and I've configured flake8 checks there: https://github.com/rocioar/flake8-django/blob/master/.circleci/config.yml#L21

I don't like black much, but it's the first time I hear about yapf, I'm going to check it out. In this project I think it makes sense to keep using flake8.

Thanks for the suggestion!

**Comment by rodolfolottin** [comment]
Oh, got it!

IMHO having the option of running it locally really encourage its use.

**Comment by stummjr** [comment]
Maybe we could write some contribution guidelines where we can encourage developers to use tools such as flake8 in their local environments.

We could tell people to do stuff like:

* run `git diff --cached | flake8 --diff` before committing; or
* install flake8 hooks on git: `flake8 --install-hook git` to run flake8 before every commit.

And whatever other things we see fit.

**Comment by bittner** [comment]
I think, the commonly used approach to run linting locally and not having to do manual setup, is integrating them with Tox in `tox.ini` and reuse that on the CI service. Example:
- [pyclean > tox.ini](https://github.com/bittner/pyclean/blob/feature/make-basic-functionality-work/tox.ini)
- [pyclean > .travis.yml](https://github.com/bittner/pyclean/blob/feature/make-basic-functionality-work/.travis.yml#L14-L17)
- [Travis build example](https://travis-ci.org/bittner/pyclean) (build stages)

**Comment by rocioar** [comment]
I have updated the project to use Github Actions, as part of that I included lint check as a job, it runs flake8
