### ISSUE TITLE
Dashes vs underscores

### ISSUE THREAD

**Issue by sobolevn** [rocioar/flake8-django#30]
Thanks for this wonderful plugin! 

I am considering to add it to our company's project template: https://github.com/wemake-services/wemake-django-template/issues/622

The only thing that bothers me is that it enforces using underscores over dashes.
There's an opinion that one should use dashes, here are some links to prove my point:
- django's docs: https://docs.djangoproject.com/en/dev/topics/http/urls/
- google webmaster: https://support.google.com/webmasters/answer/76329?hl=en

So, what can we do about it?
1. Change the default to dashes if my sources changed your opinion
2. Make it configurable if you still prefer dashes by default

P.S. Check out [my `python` linter](https://github.com/wemake-services/wemake-python-styleguide) - it might be interesting to you 🙂

**Comment by rocioar** [comment]
@sobolevn it isn't clear to me what is the argument in favour of dashes? Could you add a little more detail about it?

All the checks are configurable in `flake8`, you can create a `.flake8' file and then add this check to ignore option:

```
[flake8]
ignore = DJ04
```

You can add more checks separated by comma.

**Comment by sobolevn** [comment]
@rocioar that's not just my taste, it is how both `google` and `django` recommend to write urls:

Quoting Google:

> Consider using punctuation in your URLs. The URL http://www.example.com/green-dress.html is much more useful to us than http://www.example.com/greendress.html. We recommend that you use hyphens (-) instead of underscores (_) in your URLs.

I was asking about configuration, not just ignoring a rule. And by "configuration" I mean the following logic:
1. You edit your `.flake8` and add this option: `django-url-separator = -` or `django-url-separator = _` (might be default if you wish). 
2. Then the linting process checks for this specific character 

What do you think?

**Comment by rocioar** [comment]
@sobolevn this rule is just for the url name, it is not for the URL itself.

For example this would be valid:

`path('about-me/', name='about_me')`

**Comment by sobolevn** [comment]
Oops, did not get that. 😄 

Then I have an idea for a new rule! It would be practical to lint URL path as well.

**Comment by rocioar** [comment]
@sobolevn that would be a good check, indeed 👍
