### ISSUE TITLE
Allow max-line-length=119 by default

### ISSUE THREAD

**Issue by bittner** [rocioar/flake8-django#36]
In issue #29 you mention that you're inspired by the [Django Coding Style](https://docs.djangoproject.com/en/stable/internals/contributing/writing-code/coding-style/). However, when I install `flake8-django` and run `flake8` against a freshly generated Django project it complains about the line length:

```console
$ tox -e flake8
flake8 installed: entrypoints==0.3,flake8==3.7.7,flake8-django==0.0.4,mccabe==0.6.1,pycodestyle==2.5.0,pyflakes==2.1.1
flake8 run-test-pre: PYTHONHASHSEED='3022932512'
flake8 runtests: commands[0] | flake8
./application/settings.py:72:80: E501 line too long (91 > 79 characters)
./application/settings.py:75:80: E501 line too long (81 > 79 characters)
./application/settings.py:78:80: E501 line too long (82 > 79 characters)
./application/settings.py:81:80: E501 line too long (83 > 79 characters)
```

The Django Coding Style suggests an allowed line length of 119, though. Can you allow this by default?

Also, you're using a `max-line-length=120` yourself in the projects [tox.ini](https://github.com/rocioar/flake8-django/blob/master/tox.ini#L4). Should this be aligned, maybe?

**Comment by rocioar** [comment]
@bittner flake8 (the project for which this is a plugin) by default has a max-line-length of 79 characters. You can configure that by adding a config file to your project: http://flake8.pycqa.org/en/2.5.5/config.html#user-global

**Comment by bittner** [comment]
> @bittner flake8 (the project for which this is a plugin) by default has a max-line-length of 79 characters. You can configure that by adding a config file to your project: http://flake8.pycqa.org/en/2.5.5/config.html#user-global

Sure. And isn't the point of this plugin, being called `flake8-django` for a reason, to provide a default flake8 behavior tailored to Django?

Developers shouldn't have to worry about maintaining their own linter configurations. We should tell the linter which type of project we're dealing with, and the linter should do sensible stuff based on that fact.

Isn't that the reason you started to work on this project?

**Comment by bittner** [comment]
Any opinion on setting the default line length to 119? ([Django Coding Style](https://docs.djangoproject.com/en/stable/internals/contributing/writing-code/coding-style/))

**Comment by blueyed** [comment]
I find it too long myself.  I like 79/80 myself, but am ok with 10% more, i.e. black's 88, which also https://github.com/PyCQA/flake8-bugbear uses.
/2 cents

**Comment by bittner** [comment]
I'm fine with 88 too, as soon as the Django coding style switches to that (which may mean [DEP 0008](https://github.com/django/deps/blob/master/accepted/0008-black.rst) being accepted).

For the time being, unfortunately, the maximum line length for the Django project itself is defined as 119. We shouldn't pick an arbitrary number. But maybe 88 (following Black) is less arbitrary than 110 (following the single project called Django). Maybe you're right.

Some additional background
------------------------------

The main issue I have with the 80 default and Django is that [Django's default settings](https://github.com/django/django/blob/master/django/conf/project_template/project_name/settings.py-tpl#L87-L100) don't pass a *flake8* check. I fixed this for me in a pragmatic way by [breaking up the module path string](https://github.com/painless-software/painless-continuous-delivery/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/_/frameworks/Django/application/settings.py#L113-L130), but I think this should be addressed by an official template change or appropriate tooling (which flake8-django might be or become).

**Comment by rocioar** [comment]
I think line length is something outside of Django itself, so I would prefer to leave that decision to the user and not to the plugin.

**Comment by bittner** [comment]
Just think that way: If the official Django project itself would use `flake8-django` to enforce their own code style would you still say, "line length is something outside of Django itself"?

(Why would they? Their hypothetical goal may be not having to maintain their own, custom code style, which would then allow them to get rid of the [code style documentation](https://docs.djangoproject.com/en/stable/internals/contributing/writing-code/coding-style/) they have to maintain, or reduce it by simply pointing to this plugin.)

I feel it's irritating to use a project name that suggest a tight connection to the Django project and not support their goals.
