### ISSUE TITLE
Problems not showed in VSCode

### ISSUE THREAD

**Issue by MaickelHubner** [rocioar/flake8-django#43]
The problems in flake8-django was not showed correctly in VSCode:

![image](https://user-images.githubusercontent.com/15674062/57648250-59e3e900-759b-11e9-918e-42ed6d28dfe4.png)

![image](https://user-images.githubusercontent.com/15674062/57648266-6405e780-759b-11e9-838a-8ebf89571bb5.png)

I think this occur because of yield. Can you change to return False in run() function? I think this will correct the problem...

![image](https://user-images.githubusercontent.com/15674062/57648170-286b1d80-759b-11e9-9199-36c50e7cc60c.png)

I am using flake8-todo too, and it shows the problems:

![image](https://user-images.githubusercontent.com/15674062/57648324-99aad080-759b-11e9-8c32-8a1198c6226a.png)

I see the code in https://github.com/schlamar/flake8-todo and I think the yield is the only difference ;-)

**Comment by rocioar** [comment]
This is working for me, could you make sure that `flake8-django` is installed on your environment?
