### ISSUE TITLE
DJ04 - Linting against django docs

### ISSUE THREAD

**Issue by GitRon** [rocioar/flake8-django#52]
Hi @rocioar 

I wonder what the use of `DJ04` might be. If you look at the django docs [https://docs.djangoproject.com/en/3.0/topics/http/urls/#examples](url), using dahes is the way to go.

Best
Ronny

**Comment by rocioar** [comment]
You are right, we should remove that check altogether.

**Comment by GitRon** [comment]
@rocioar Thanks for all your work during the holidays! When will you release a new version? :)

**Comment by rocioar** [comment]
@GitRon I think it will be next weekend, I should have a bit of time to work on it again.

**Comment by GitRon** [comment]
Awesome!
