### ISSUE TITLE
The plugin cannot work by flake8 `--load-plugins`.

### ISSUE THREAD

**Issue by potoo0** [rocioar/flake8-django#55]
The plugin cannot work by flake8 `--load-plugins`.
I want to use this plugin in vscode, but when I add `--load-plugins flake8_django`, flake8 doesn't work anymore.
Here is my vscode `settings`:

```json
"python.linting.enabled": true,
"python.linting.pylintEnabled": false,
"python.linting.flake8Enabled": true,
"python.linting.flake8Args": [
    // "--load-plugins", "flake8-django",
    "--load-plugins", "flake8_django",
],
```
Thanks ever so.

**Comment by rocioar** [comment]
`--load-plugins` it's an option for pylint, VSCode comes with Pylint enabled by default. To enable `flake8` instead you have to set `python.linting.flake8Enabled` to `true`. In order for plugins to run you just have to have them installed on your environment.
