### ISSUE TITLE
Document examples for each warning (in Wiki)

### ISSUE THREAD

**Issue by bittner** [rocioar/flake8-django#63]
It would be helpful if there were examples of how to fix warnings that are reported by *flake8-django*.

Since there is no separate documentation yet (and I don't like to make the README more lengthy) I'd suggest to create a Wiki page, or even separate pages for each warning,

- explaining the warning,
- maybe showing an example of a "wrong" code
- and how "correct" code would look like in comparison.

## Example

This could be somewhat in the vein of http://pylint-messages.wikidot.com/all-codes

## Motivation

Since you bumped the version from 0.0.4 to 1.0.0 I'm getting a new, unexpected warning:

> DJ05 Missing namespace in urls include()

That is probably okay, but now I'm puzzled how to fix that. (No worries, I'll eventually find out!)

I'm a little bit worried that the typical developer reaction kicks in when reported warnings are not super-easy to fix: Disable the linter all together.

**Comment by rocioar** [comment]
Thanks a lot for bringing this up. I think you are right, we will need this guide if we want people to adopt it. Also, it would help us figure out if all the checks make sense, or if they are too opinionated and lack reasoning.

**Comment by rocioar** [comment]
@bittner I have created a wiki page documenting each of the checks: https://github.com/rocioar/flake8-django/wiki. Hope this is helpful, I will close the issue for now.

**Comment by bittner** [comment]
Nice! :+1: 

Maybe you could add a "docs" badge to the top of the [README](https://github.com/rocioar/flake8-django#flake8-django), or to the table items in the [List of warnings](https://github.com/rocioar/flake8-django#list-of-warnings) section that would link to the wiki pages.
