### ISSUE TITLE
Policy for future versions and rules

### ISSUE THREAD

**Issue by sobolevn** [rocioar/flake8-django#77]
Hi, @rocioar! Thanks a lot for building and maintaining this library. 

I want to raise an important question with this issue. After `1.1.0` some of the rules we rely on are gone.
I am talking about: `DJ09`, `DJ10`, `DJ11`. And it is very sad!

In my experience, deleting rules is not a good practice. Because they do bring the most part of the value to this project!
Instead, there are several way to address problems which were raised in, for example, this issue: https://github.com/rocioar/flake8-django/issues/64

1. Propose to use `noqa` for a specific case user does not want to have this rules applied
2. Propose to use `per-file-ignores`
3. Propose to use `ignore`
4. When you understand than this rule is too strict, too opinionated, or too complex, then it is possible to make it disabled by default
5. And only then we can say that deleting a rule is a the only thing left. I only use this practice when the rule is no longer required or is just wrong

So, what do you think about approving this policy and bringing back the deleted rules under some of the conditions above?

Related:
- https://github.com/rocioar/flake8-django/issues/64
- https://github.com/rocioar/flake8-django/commit/41989771f70ed72dd3924c2f89dd0f55913a593e

Cheers!

**Comment by rocioar** [comment]
Hi @sobolevn, thanks for opening this issue.

I removed `DJ09`, `DJ10` and `DJ11` since I think they are wrong. I wrote the [wiki page](https://github.com/rocioar/flake8-django/wiki) over the weekend with explanations for each of the Rules (with sections such as: do, don't and reasons behind the rule), but I couldn't really find **any** reasonable explanation for these rules. Can you think of one?

`DJ05` case is a bit different. The idea of the Rule is correct, but there is no way of knowing when some code is correct and when not since there are plenty of cases in which not providing a namespace is correct. Using just the `ast` tree we don't have a way to tell. So I decided to remove it to avoid lots of false-positive warnings.

Regarding 4. Do you know if it's possible to make a rule disabled by default on the plugin itself? If it is up to the user, then I prefer to leave these Rules out.

**Comment by sobolevn** [comment]
> I removed DJ09, DJ10 and DJ11 since I think they are wrong

And I think that they are great! Let me illustrate it with my own experience.

We live in Russia and create software for Russian clients. And we do love to have everything translated into our native language. To do that we need to translate model names as well: we use `gettext` and `verbose_name` and `verbose_name_plural`

And this checked helped me many times when I forgot to do that.
P.S. I would even suggest to add a new rule: check that `verbose_name` and `verbose_name_plural` use `_` function call. Should I open a new issue for that?

> DJ05 case is a bit different

I would say that namespaces are always a good idea. `Namespaces are one honking great idea -- let's do more of those!`
In case if user thinks that it is okay to not add a namespace, then `noqa`, `per-file-ignores, or `ignore`. We cannot and should not care about being 100% correct. In my vision, static analysis is more about constant notifications: you forgot to use the best practice here and there. 

If you believe that this rule should not be enabled by default, that's fine.

> Regarding 4. Do you know if it's possible to make a rule disabled by default on the plugin itself?

Yes, there's such a feature: https://github.com/PyCQA/flake8-bugbear/blob/master/bugbear.py#L78 You can also be interested in `--enable-extensions`

I got a lot of suggestions to split my project (https://github.com/wemake-services/wemake-python-styleguide) into multiple levels of strictness. Maybe we can think about the same idea here?

In this case, it is possible to have something like this:

1. Base, checks that are 100% correct
2. Recommended, with some advanced checks
3. Strict, with everything activated

It can be activated with `--django-strictness=strict` or similar

And in this case you can safely move some rules between groups instead of deleting them.
How do you like this idea?

**Comment by rocioar** [comment]
I like the idea of disabling them by default for the entire plugin, I think that fixes the issue of new users getting a lot of warnings on issues they don't need to address, but it also allows other users to enable that check if they wanted.

With that we could bring back `DJ10`, `DJ11`, and create a new rule for translations. Making them all disabled by default.

I would like to give it more thought to the strictness level, it might be a good idea. But we could start by re-enabling the checks and disabling them by default.

Regarding `DJ05` I will spend a bit more time thinking on the use cases, and see if it makes sense to bring it back. From what I've seen so far, there were so many false-positives that people would have to worry too much about per file, or per line ignores.

**Comment by freezed** [comment]
Thanks for this discussion and the work, my teammate [made a comment](https://github.com/rocioar/flake8-django/commit/191f13e6b40f327899c316721cb5f15ed58254bf#commitcomment-39201951) about the _popup venue_ of `DJ05`, and we where waiting about it :pray:

**Comment by avallbona** [comment]
> Hi, @rocioar! Thanks a lot for building and maintaining this library.
> 
> I want to raise an important question with this issue. After `1.1.0` some of the rules we rely on are gone.
> I am talking about: `DJ09`, `DJ10`, `DJ11`. And it is very sad!
> 
> In my experience, deleting rules is not a good practice. Because they do bring the most part of the value to this project!
> Instead, there are several way to address problems which were raised in, for example, this issue: #64
> 
> 1. Propose to use `noqa` for a specific case user does not want to have this rules applied
> 2. Propose to use `per-file-ignores`
> 3. Propose to use `ignore`
> 4. When you understand than this rule is too strict, too opinionated, or too complex, then it is possible to make it disabled by default
> 5. And only then we can say that deleting a rule is a the only thing left. I only use this practice when the rule is no longer required or is just wrong
> 
> So, what do you think about approving this policy and bringing back the deleted rules under some of the conditions above?
> 
> Related:
> 
> * #64
> * [4198977](https://github.com/rocioar/flake8-django/commit/41989771f70ed72dd3924c2f89dd0f55913a593e)
> 
> Cheers!

I agree with @sobolevn that these rules `DJ09`, `DJ10`, `DJ11` make a lot of sense, specially when you're developing mainly not in english. I added these rules to this project and we already discussed that they could be disabled: https://github.com/rocioar/flake8-django/pull/35#issuecomment-489467972
I did not understand the decision of removing them. I hope this decision could be reconsidered.

Kind regards.

**Comment by rocioar** [comment]
@avallbona as I mentioned on the comment above, I will re-enable them but make them disabled by default. Thanks!

**Comment by rocioar** [comment]
@avallbona I don't see a reason to enable back DJ09 though (the one that checks that the Meta class is defined). I think `DJ10` and `DJ11` will already check for `verbose_name` inside the Meta inner class, so they would implicitly cover `DJ09`. What other reason could there be for having the `Meta` class defined if it's not for `verbose_name` and `verbose_name_plural`?

**Comment by sobolevn** [comment]
Yes, I agree. `class Meta:` is not required by itself. Its content is important!

**Comment by avallbona** [comment]
:Ok, it makes sense :+1:
