### ISSUE TITLE
DJ01 with ImageField

### ISSUE THREAD

**Issue by mrswats** [rocioar/flake8-django#82]
Writing today some code I found this
```
image_downloader/models.py:38:13: DJ01 Avoid using null=True on string-based fields such ImageField. [flake8-django]
  image = models.ImageField(upload_to=path_to_upload, null=True, blank=True)
          ^
```
And I wonder what's going on here? I am using [django-storages](https://django-storages.readthedocs.io/en/latest/) to store my images on S3 and, in the end, a URL is stored in the database, that's true, but this error makes no sense whatsoever, correct? Am I missing something?

**Comment by rocioar** [comment]
Good catch, Django won't allow an empty value to be set on an ImageField, the empty value is actually null so this check is not correct.

Would you like to contribute by removing the ImageField from the List of checks, as it was on this PR with the UUIDField: https://github.com/rocioar/flake8-django/pull/81/ ?

**Comment by mrswats** [comment]
Sure! I will take a look at it later!

**Comment by mrswats** [comment]
Solved by https://github.com/rocioar/flake8-django/pull/84.

**Comment by rsalmaso** [comment]
:thinking: 
https://code.djangoproject.com/ticket/10244
FileField/ImageField are not a CharField, but they behave the same.

and in https://docs.djangoproject.com/en/3.1/ref/models/fields/#filefield

> FileField instances are created in your database as varchar columns with a default max length of 100 characters. As with other fields, you can change the maximum length using the max_length argument.

I think it should be reverted.

**Comment by rocioar** [comment]
@rsalmaso this check was not correct since FileField and ImageField get set to null when there is an empty value so null=True is a valid option: https://github.com/django/django/blob/master/django/forms/fields.py#L553

The fact that they both inherit from CharField, in this case, doesn't change anything, because they both override the `to_python` method.
