### ISSUE TITLE
missing compatibility with flake8 >= v4.0.0

### ISSUE THREAD

**Issue by JanMalte** [rocioar/flake8-django#93]
maybe this is just a declaration issue and only needs a small change and a new release

**Comment by timohermans** [comment]
So I see this has already been merged to master. Any indication on a version release? :)

**Comment by edouardruiz** [comment]
Hi @rocioar! Thanks for this flake8 plugin, very useful for us! I was wondering if you're planning a new release with #92 to make flake8-django compatible with flake8 >= 4.0.0?

**Comment by mredaelli** [comment]
That would be great :)

**Comment by stephenross** [comment]
@rocioar It looks like #92 is the only code not in the latest release, could you please cut a new release so that the change to allow flake8 4.x is available to install from package managers?

**Comment by MuslimBeibytuly** [comment]
@rocioar hi, is repo maintained? is it planned to make release for compatibility?

**Comment by MuslimBeibytuly** [comment]
@JanMalte @timohermans @edouardruiz @mredaelli seems like @rocioar is offline and repository is abandoned for 5th months now, is there any instruction on what to do?

**Comment by JanMalte** [comment]
@MuslimBeibytuly well, you could try to reach @rocioar via other channels

If there is no success, it might be necessary to fork the project and publish it under a new name on pypi

**Comment by rocioar** [comment]
I'll cut a new release today, sorry if this took too long!

**Comment by rocioar** [comment]
Done, new version 1.1.3 is available in PyPi
